/*
 * ----------------------------------------------------------------------
 *  MAIN PROGRAM - generated by the Rappture Builder
 * ----------------------------------------------------------------------
 */
#include "rappture.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>

int main(int argc, char * argv[]) {
    /* stuff needed for Rappture library */
    RpLibrary* io;
    const char* data; char line[255];
    int err;

    int value1;  /* for input.integer(value1) */
    int value2;  /* for input.integer(value2) */
    int value3;  /* for output.integer(value3) */
    

    /* open the XML file containing the run parameters */
    io = rpLibrary(argv[1]);

    if (io == NULL) {
        /* cannot open file or out of memory */
        printf("FAILED loading Rappture data\n");
        exit(1);
    }

    /*
     *********************************************************
     * Get input values from Rappture
     *********************************************************
     */
    
    /* get input value for input.integer(value1) */
    rpGetString(io,"input.integer(value1).current", &data);
    value1 = atoi(data);
    
    /* get input value for input.integer(value2) */
    rpGetString(io,"input.integer(value2).current", &data);
    value2 = atoi(data);
    

    /*
     *********************************************************
     *  Add your code here for the main body of your program
     *********************************************************
     */

    /* spit out progress messages as you go along... */
    rpUtilsProgress(0, "Starting...");
    rpUtilsProgress(5, "Loading data...");
    value3 = value1-value2;
    rpUtilsProgress(50, "Half-way there");
    rpUtilsProgress(100, "Done");

    /*
     *********************************************************
     * Save output values back to Rappture
     *********************************************************
     */
    
    /* save output value for output.integer(value3) */
    sprintf(line, "%d\n", value3);
    rpPutString(io, "output.integer(value3).current", line, RPLIB_OVERWRITE);
    

    rpResult(io);
    exit(0);
}
